# Generated by Django 4.2.10 on 2024-02-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(default=1, max_length=255, upload_to=''),
            preserve_default=False,
        ),
    ]
