# Generated by Django 4.2.10 on 2024-02-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
    ]
